# -*- coding: utf-8 -*-
"""banned_book_state.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYMAP00NgX_p0CxULHJI5usgLzAHOwhh
"""

import pandas as pd
import geopandas as gpd
import streamlit as st
import folium
from streamlit_folium import st_folium
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

st.set_page_config(layout="wide")
st.title("Banned Books by State")

path = "Grid view.csv"
df = pd.read_csv(path)
state_bans = df['State'].value_counts().reset_index()
state_bans.columns = ['STATE_NAME', 'Ban_Count']

usa = gpd.read_file("cb_2025_us_state_20m.zip")
merged = usa.merge(state_bans, left_on='NAME', right_on='STATE_NAME', how='left')
merged['Ban_Count'] = merged['Ban_Count'].fillna(0)

m = folium.Map(location=[37.8, -96], zoom_start=4, tiles="cartodbpositron")

choropleth = folium.Choropleth(
    geo_data=merged,
    name="choropleth",
    data=merged,
    columns=["NAME", "Ban_Count"],
    key_on="feature.properties.NAME",
    fill_color="YlOrRd",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Banned Books Count"
).add_to(m)

for idx, row in merged.iterrows():
    if row.geometry is not None:
        books_in_state = df[df['State'] == row['NAME']]['Title'].tolist()
        book_list_str = "<br>".join(books_in_state[:10]) if books_in_state else "None"
        popup_text = f"<b>{row['NAME']}</b><br>Total Bans: {int(row['Ban_Count'])}<br><br><b>Sample Books:</b><br>{book_list_str}"

        folium.GeoJson(
            row.geometry,
            style_function=lambda x: {'fillColor': '#00000000', 'color': '#00000000'},
            tooltip=f"{row['NAME']}: {int(row['Ban_Count'])} bans",
            popup=folium.Popup(popup_text, max_width=300)
        ).add_to(m)

map_data = st_folium(m, width=1000, height=600)

bins = [-1, 0, 10, 100, 500, 1000, 3000, 6000]
labels = ['0', '1-10', '11-100', '101-500', '501-1,000', '1,001-3,000', '3,001-6,000']
colors = ['#e5e7eb', '#fde68a', '#fcd34d', '#f97316', '#ea580c', '#dc2626', '#7f1d1d']

merged['bin'] = pd.cut(merged['Ban_Count'], bins=bins, labels=labels)
color_dict = dict(zip(labels, colors))
merged['color'] = merged['bin'].map(color_dict)

fig, ax = plt.subplots(figsize=(12, 8))
merged.plot(ax=ax, color=merged['color'], edgecolor='black', linewidth=0.5)

ax.set_xlim([-130, -65])
ax.set_ylim([24, 50])
ax.axis('off')

legend_patches = [mpatches.Patch(facecolor=c, edgecolor='black', label=l) for l, c in zip(labels, colors)]
ax.legend(handles=legend_patches, loc='lower left', title="Banned Books", frameon=True, ncol=2)

plt.title("Banned Books by State", fontweight="bold")
plt.figtext(0.12, 0.08, "Source: PEN America", fontsize=10, style='italic', color='dimgray')

# Render Matplotlib plot in Streamlit
st.pyplot(fig)
st.caption("Source: PEN America")